[package]
name = "novelai-metadata-organizing-tool"
version = "0.1.0"
description = "NovelAI PNG metadata organizer"
authors = ["Achilng"]
edition = "2021"
license = "MIT"

[lib]
name = "novelai_metadata_organizing_tool_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }
flate2 = "1.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
rust_xlsxwriter = "0.95.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sevenz-rust = "0.6.1"
tauri = { version = "2.11.2", features = [] }
tauri-plugin-dialog = "2.7.1"
thiserror = "2.0"
unrar-ng = "0.7.7"
walkdir = "2.5.0"
zip = { version = "7.2.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
crc32fast = "1.5"
